version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: deckbuilder-mongodb
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: bee
      MONGO_INITDB_ROOT_PASSWORD: IwTLJS2025
    volumes:
      - deckbuilder-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: deckbuilder-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://bee:IwTLJS2025@mongodb:27017
      - PORT=5000
    depends_on:
      - mongodb

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: deckbuilder-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  deckbuilder-data: